package com.qa.spring.games.enums;

public enum GameGenre {

    PLATFORMER, SHOOTER, FIGHTING, STEALTH, SURVIVAL, RHYTHM, PUZZLE, METROIDVANIA, ADVENTURE, ACTION, RPG, MMORPG, STRATEGY, SIMULATOR, SPORTS, RACING

}
